name: Continuous Integration

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

env: 
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Cargo Check
        run: |
          cd initialize_ssh && cargo check --verbose
