---
configure_ssh_sshd_config:
  Protocol: 2
  Port: 22
  PermitRootLogin: 'no'
  PasswordAuthentication: 'no'
  PermitEmptyPasswords: 'no'
  StrictModes: 'yes'
  IgnoreRhosts: 'yes'
  UsePAM: 'yes'
  X11Forwarding: 'no'