---
- name: "Ensure we have a sudo group"
  ansible.builtin.group:
    name: "{{ automation_group }}"
    state: present

- name: "Add username {{ github_user }} "
  become: true
  ansible.builtin.user:
    name: "{{ github_user }}"
    group: "{{ automation_group }}"
    comment: "Ansible Automation User"

- name: "Set Authorized Keys from Github"
  ansible.posix.authorized_key:
    user: "{{ github_user }}"
    state: present
    key: http://github.com/{{ github_user }}.keys

- name: Add generally necessary packages
  ansible.builtin.package:
    state: present
    name:
      - curl

- name: "Create Mount Directory"
  with_items: "{{ folders_to_mount }}"
  ansible.builtin.file:
    path: /mnt/{{ item }}
    group: "docker"
    state: directory
    mode: u=rwx,g=rx,o=rx
