---
- name: "Ensure we have a sudo group"
  group:
    name: "sudo"
    state: present

- name: "Add {{ github_user }} username"
  become: true
  ansible.builtin.user:
    name: "{{ github_user }}"
    group: "sudo"
    comment: "Ansible Automation User"

- name: "Set Authorized Keys from Github"

  ansible.posix.authorized_key:
    user: "{{ github_user }}"
    state: present
    key: http://github.com/{{ github_user }}.keys
