---
- name: Install SSH Packages
  ansible.builtin.package:
    use: "{{ package_type | default('auto') }}"
    name: 
      - openssh-server
      - fail2ban
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Harden sshd
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: '^#?\s*{{ item.key }}.*'
    value: "{{ item.key }} {{ item.value }}"
    validate: "sshd -t -f %s"
  loop: "{{ configure_ssh_sshd_config | dict2items }}"
  notify: Reload SSHd