---
- name: Ensure Group "docker" Exists"
  ansible.builtin.group:
    name: "docker"
    state: present
  register: group_out

- name: "Ensure User Exists {{ automation_user }} "
  ansible.builtin.user:
    user: "{{ automation_user }}"
  register: user_out

- name: Set Docker Group Id Fact
  ansible.builtin.set_fact:
    docker_group_id: "{{ group_out.gid }}"

- name: "Set User Id Fact {{ automation_user }} "
  ansible.builtin.set_fact:
    automation_user_id: "{{ user_out.uid }}"

- name: "Install Packages For Samba"
  ansible.builtin.package:
    state: present
    name:
      - psmisc
      - cifs-utils

# Used for molecule, we can assume that the home folder exists.
# - name: "Ensure Home Folder Exists"
#   ansible.builtin.file:
#     path: /home/{{ automation_user }}
#     state: directory

- name: "Add SambaShare Mounts on Boot"
  with_items: "{{ folders_to_mount }}"
  notify: "Reload Systemd Daemon"
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    line: "//{{ samba_host }}/{{ item }}\t/mnt/{{ item }}\tcifs\tcredentials=/home/{{ automation_user }}/.credentials,uid={{ automation_user_id }},gid={{ docker_group_id }}"

- name: "Write Credentials File"
  ansible.builtin.template:
    src: files/credentials.j2
    dest: /home/{{ automation_user }}/.credentials
    owner: "{{ automation_user }}"
    group: "sudo"
    mode: u=rw,g=r,o=r
