---
- name: Download Mullvad Signing Key
  ansible.builtin.get_url:
    url: https://repository.mullvad.net/deb/mullvad-keyring.asc
    dest: /usr/share/keyrings/mullvad-keyring.asc
    mode: "0644"

- name: Create Mullvad Apt Repository file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/mullvad.list
    state: touch
    owner: root
    group: root
    mode: "0644"

- name: Add Mullvad to Apt Repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/mullvad.list
    line: deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch={{ deb_architecture }}] https://repository.mullvad.net/deb/stable {{ version_codename }} main

# The mullvad package requires systemd to successfully install
# We also cannot use molecule to test this because no docker container because systemd doesn't exist on docker containers
- name: Install mullvad-vpn
  ansible.builtin.apt:
    update_cache: true
    name:
      - systemd
      - mullvad-vpn
