---
- name: Update Mullvad relay
  ansible.builtin.shell: mullvad relay update

- name: Allow mullvad local traffic
  ansible.builtin.shell: mullvad lan set allow

- name: Set Region And City
  ansible.builtin.shell: mullvad relay set location {{ vpn_country }} {{ vpn_city }}
# - name: Logout from mullvad
#   ansible.builtin.shell: mullvad account logout

# - name: Login into mullvad
#   ansible.builtin.shell: mullvad account login {{ mullvad_account }}

# # Have to add this
#sudo ip route add 192.168.2.0/24 via 192.168.4.1 dev wlp4s0
