---
- name: Update Mullvad relay
  ansible.builtin.shell: mullvad relay update

- name: Allow mullvad local traffic
  ansible.builtin.shell: mullvad lan set allow

- name: Set Region And City
  ansible.builtin.shell: mullvad relay set location {{ vpn_country }} {{ vpn_city }}

- name: Enable mullvad auto-connect
  ansible.builtin.shell: mullvad auto-connect set on

- name: Logout from mullvad
  ansible.builtin.shell: mullvad account logout

- name: Login Into Mullvad
  ansible.builtin.shell: mullvad account login {{ mullvad_account }}

- name: "Connect To VPN"
  ansible.builtin.shell: mullvad connect
