---
# handlers file for media_services
- name: "Restart Docker"
  service:
    name: docker
    state: restarted
    enabled: true
  become: true

- name: "Configure Docker"
  include_tasks: handlers/configure-docker.yaml