name: CI for initialize-ssh

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: run cargo check
      run: |
        cd initialize_ssh && cargo check --verbose
    - name: Run cargo fmt
      run: |
        cd initialize_ssh && cargo fmt --verbose
